<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>

    <AssemblyName>SeasonalSLSBridge</AssemblyName>
    <RootNamespace>SeasonalSLSBridge</RootNamespace>

    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>

    <Reference Include="BepInEx">
      <HintPath>C:\Users\odiii\AppData\Roaming\Thunderstore Mod Manager\DataFolder\Valheim\profiles\Default\BepInEx\core\BepInEx.dll</HintPath>
    </Reference>

    <Reference Include="0Harmony">
      <HintPath>C:\Users\odiii\AppData\Roaming\Thunderstore Mod Manager\DataFolder\Valheim\profiles\Default\BepInEx\core\0Harmony.dll</HintPath>
    </Reference>

    <Reference Include="assembly_valheim">
      <HintPath>D:\SteamLibrary\steamapps\common\Valheim\valheim_Data\Managed\assembly_valheim.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine">
      <HintPath>D:\SteamLibrary\steamapps\common\Valheim\valheim_Data\Managed\UnityEngine.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine.CoreModule">
      <HintPath>D:\SteamLibrary\steamapps\common\Valheim\valheim_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>

  </ItemGroup>

</Project>
